title: Example component
context:
    text: As of February this year, Phaser version 3 was released and I’ve been paying a bit more attention and learning what this new, ground-up rebuild has to offer. I’m finding it a lot of fun and can see a lot of potential for creating ubiquitous, browser-based 2D games.
